---
# tasks file for keepalived
- name: keepalived install and setup 
  block:
    - name: stop keepalived if needed
      ansible.builtin.systemd_service:
        name: keepalived
        state: stopped
      ignore_errors: true
    - name: Ensure /etc/keepalived ist available
      ansible.builtin.file:
        path: /etc/keepalived
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Install keepalived
      ansible.builtin.dnf:
        name: keepalived
        state: latest
    - name: Copy keepalived config
      ansible.builtin.template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: '644'
    - name: Start keepalived
      ansible.builtin.systemd_service:
        name: keepalived
        state: started
        enabled: true
  tags:
    - keepalived

